-- Read-only post-promotion report. Run with psql -v ON_ERROR_STOP=1.
WITH gates AS (
  SELECT 'document_usage_engine_present' AS gate, CASE WHEN to_regclass('public.document_usage_events') IS NOT NULL AND to_regprocedure('public.resolve_free_document_usage_cycle(timestamptz,timestamptz)') IS NOT NULL AND to_regprocedure('public.create_document_with_usage(uuid,text,uuid,uuid,jsonb)') IS NOT NULL THEN 'PASS' ELSE 'FAIL' END AS status, 'usage table and RPCs' AS detail
  UNION ALL SELECT 'usage_hardening_rls', CASE WHEN (SELECT relrowsecurity FROM pg_class WHERE oid='public.document_usage_events'::regclass) AND NOT has_table_privilege('anon','public.document_usage_events','INSERT,UPDATE,DELETE') AND NOT has_table_privilege('authenticated','public.document_usage_events','INSERT,UPDATE,DELETE') AND NOT has_table_privilege('service_role','public.document_usage_events','INSERT,UPDATE,DELETE') THEN 'PASS' ELSE 'FAIL' END, 'RLS enabled and direct writes revoked'
  UNION ALL SELECT 'r1_entitlement_contract', CASE WHEN (SELECT count(*) FROM pg_attribute WHERE attrelid='public.entitlements'::regclass AND attname IN ('invoice','quote','pdf_branding','client_approval','approval_scope') AND NOT attisdropped)=5 AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid='public.entitlements'::regclass AND c.conname='entitlements_plan_check') AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid='public.entitlements'::regclass AND c.conname='entitlements_pdf_branding_check') AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid='public.entitlements'::regclass AND c.conname='entitlements_approval_scope_check') THEN 'PASS' ELSE 'FAIL' END, 'R1 fields/checks present'
  UNION ALL SELECT 'subscription_contract', CASE WHEN EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid='public.subscriptions'::regclass AND attname='paddle_price_id' AND NOT attisdropped) AND EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid='public.subscriptions'::regclass AND attname='latest_event_occurred_at' AND NOT attisdropped) AND EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid='public.subscriptions'::regclass AND c.conname='subscriptions_status_check' AND pg_get_constraintdef(c.oid) ILIKE '%paused%') AND NOT EXISTS (SELECT 1 FROM public.subscriptions GROUP BY user_id HAVING count(*)>1) AND NOT EXISTS (SELECT 1 FROM (SELECT NULLIF(BTRIM(paddle_subscription_id),'') AS paddle_id FROM public.subscriptions WHERE NULLIF(BTRIM(paddle_subscription_id),'') IS NOT NULL GROUP BY 1 HAVING count(*)>1) d) THEN 'PASS' ELSE 'FAIL' END, 'R2 subscription columns/status/uniqueness'
  UNION ALL SELECT 'billing_event_contract', CASE WHEN (SELECT count(*) FROM pg_attribute WHERE attrelid='public.billing_events'::regclass AND attname IN ('occurred_at','applied') AND NOT attisdropped)=2 AND EXISTS (SELECT 1 FROM pg_index ix WHERE ix.indrelid='public.billing_events'::regclass AND ix.indisunique AND ix.indpred IS NULL AND ix.indexprs IS NULL AND ix.indnkeyatts=1 AND ix.indkey[0]=(SELECT attnum FROM pg_attribute WHERE attrelid='public.billing_events'::regclass AND attname='event_id')) AND NOT EXISTS (SELECT 1 FROM pg_class WHERE relnamespace='public'::regnamespace AND relname='billing_events_event_id_unique' AND relkind='i') THEN 'PASS' ELSE 'FAIL' END, 'event timestamp/applied and R3 semantic final state'
  UNION ALL SELECT 'webhook_function_authority', CASE WHEN to_regprocedure('public.apply_paddle_webhook_event(text,text,uuid,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz,jsonb,boolean,boolean,boolean,text,boolean,boolean,text,boolean,boolean,boolean,boolean)') IS NOT NULL AND has_function_privilege('service_role','public.apply_paddle_webhook_event(text,text,uuid,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz,jsonb,boolean,boolean,boolean,text,boolean,boolean,text,boolean,boolean,boolean,boolean)','EXECUTE') AND NOT has_function_privilege('anon','public.apply_paddle_webhook_event(text,text,uuid,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz,jsonb,boolean,boolean,boolean,text,boolean,boolean,text,boolean,boolean,boolean,boolean)','EXECUTE') AND NOT has_function_privilege('authenticated','public.apply_paddle_webhook_event(text,text,uuid,text,text,text,text,text,text,timestamptz,timestamptz,timestamptz,jsonb,boolean,boolean,boolean,text,boolean,boolean,text,boolean,boolean,boolean,boolean)','EXECUTE') THEN 'PASS' ELSE 'FAIL' END, 'accepted exact signature and service_role-only execute'
  UNION ALL SELECT 'payment_authority_preserved', CASE WHEN to_regprocedure('public.record_invoice_payment(uuid,uuid,integer,text,text,timestamptz,text)') IS NOT NULL THEN 'PASS' ELSE 'FAIL' END, 'seven-parameter record_invoice_payment preserved'
  UNION ALL SELECT 'quote_invoice_authority_preserved', CASE WHEN EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conrelid='public.invoices'::regclass AND c.confrelid='public.quotes'::regclass AND c.contype='f') THEN 'PASS' ELSE 'FAIL' END, 'Quote -> Invoice boundary preserved'
)
SELECT gate,status,detail FROM gates ORDER BY gate;
