import {
  Home,
  FileText,
  Receipt,
  Users,
  UserCircle,
  IdCard,
  Settings,
  BarChart,
  Search,
  CreditCard,
  Mail,
  Plus,
  Trash2,
  Check,
  AlertTriangle,
  Info,
  LogOut,
  Sparkles,
  ArrowRight,
  Eye,
  Download,
  Share2,
  DollarSign,
  Calendar,
  Clock,
  MapPin,
  Globe,
  HelpCircle,
  Menu,
  X,
  FileSpreadsheet,
  Settings2,
  Copy,
  ChevronRight,
  Send,
  Loader2,
  Lock,
} from 'lucide-react';

export const Icons = {
  // Navigation mapping requested by USER
  overview: Home,
  dashboard: Home,
  quotes: FileText,
  invoices: Receipt,
  clients: Users,
  portal: UserCircle,
  profile: IdCard,
  settings: Settings,
  analytics: BarChart,
  seo: Search,
  payments: CreditCard,
  
  // Custom dashboard navigation support
  leads: Mail,
  studio: Sparkles,

  // Action & Util icons
  Plus: Plus,
  Trash: Trash2,
  Check: Check,
  Warning: AlertTriangle,
  Info: Info,
  LogOut: LogOut,
  Sparkles: Sparkles,
  ArrowRight: ArrowRight,
  Eye: Eye,
  Download: Download,
  Share: Share2,
  Dollar: DollarSign,
  Calendar: Calendar,
  Clock: Clock,
  MapPin: MapPin,
  Globe: Globe,
  Help: HelpCircle,
  Menu: Menu,
  Close: X,
  FileSpreadsheet: FileSpreadsheet,
  Settings2: Settings2,
  Copy: Copy,
  ChevronRight: ChevronRight,
  Send: Send,
  Loader: Loader2,
  Lock: Lock,
};
